# Generated by Django 4.2.14 on 2024-07-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_accessibility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', 'location', 'name']},
        ),
    ]
