# Generated by Django 4.2.6 on 2024-07-19 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import index.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=17, validators=[index.validators.validate_customer_phone_number])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=350)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitedUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[index.validators.validate_customer_phone_number])),
                ('city', models.CharField(blank=True, max_length=50, validators=[index.validators.validate_customer_city])),
                ('zip_code', models.CharField(blank=True, max_length=10, validators=[index.validators.validate_customer_zip_code])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
